[server]
runOnSave = true
maxUploadSize = 200
connectTimeout = 10

[browser]
serverAddress = "localhost"
gatherUsageStats = false

[theme]
base = "light"

[client]
showErrorDetails = true
toolbarMode = "minimal"

[runner]
# Use Python 3.11 which still has asyncore support
pythonVersion = "3.11"